language: ruby
sudo: false
cache: bundler
rvm:
  - 1.8.7
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.1.8.0
  - rbx-3.69
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-9.1.8.0
    - rvm: rbx-3.69
